version: '3'

services:

  master:
    image: redis:3-alpine
    ports:
      - "6379:6379"
  slave:
    image: redis:3-alpine
    command: redis-server --port 6381 --slaveof redis-master 6379
    ports:
      - "6381:6381"
    links:
      - master:redis-master
  sentinel:
    build: sentinel
    ports:
      - "26379:26379"
    environment:
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=5000
    links:
      - master:redis-master
      - slave
